// import {
//   fakeCupons,
//   fakeDoadores,
//   fakeDonations,
//   fakeInstituicoes,
//   fakePagamentos,
// } from "../mockedData/mockedData";
import { Doacao } from "../models/Doacao";
import { Instituicao } from "../models/Instituição";

export class DonationsService {
  /**
   * execute
   */ // Generated by https://quicktype.io

  public CreateDonation(instituicao: Instituicao, donationValue: string) {
    const newdonate = {
      idDoador: "60ac36fa1f354d9b256cd5a6",
      idInstituicao: instituicao.id,
      pagamento: {
        valor: donationValue,
        nomeCartao: "JOAO SILVA",
        numeroCartao: "XXXXXXXXXXXX1234",
        codigoSegurancaCartao: "XXX",
        validadeCartao: "XXXXX",
        statusProcessamento: "Pago",
      },
      idCupom: ["string"],
      valor: donationValue,
    };
    console.log(newdonate);
  }
}
